# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  client:
    image: os_client
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:5038
